// swift-tools-version: 6.0
// Generated by Genesis v0.1.0-phase1k2.
import PackageDescription

let package = Package(
    name: "IAMContext",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        .library(name: "EmployeeAccessAggregate", targets: ["EmployeeAccessAggregate"]),
        .executable(name: "IAMContextServer", targets: ["IAMContextServer"]),
        .executable(name: "EnrollStaffs", targets: ["EnrollStaffs"]),
        .executable(name: "RevokeAllPrivileges", targets: ["RevokeAllPrivileges"]),
        .library(name: "IAMContextShared", targets: ["IAMContextShared"]),
    ],
    dependencies: [
        .package(url: "https://github.com/gradyzhuo/swift-ddd-kit.git", from: "0.3.0"),
        .package(url: "https://github.com/apple/swift-openapi-generator", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-openapi-runtime", from: "1.0.0"),
        .package(url: "https://github.com/swift-server/swift-openapi-hummingbird", from: "2.0.0"),
        .package(url: "https://github.com/hummingbird-project/hummingbird", from: "2.0.0"),
        .package(url: "https://github.com/apple/swift-log", from: "1.0.0"),
        .package(url: "https://github.com/grpc/grpc-swift-2.git", from: "2.0.0"),
        .package(url: "https://github.com/grpc/grpc-swift-nio-transport.git", from: "2.0.0"),
        .package(url: "https://github.com/grpc/grpc-swift-protobuf.git", from: "2.0.0"),
        .package(url: "https://github.com/grpc/grpc-swift-extras.git", from: "2.1.0"),
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.33.3"),
    ],
    targets: [
        .target(
            name: "EmployeeAccessAggregate",
            dependencies: [
                .product(name: "DDDKit", package: "swift-ddd-kit"),
                .target(name: "IAMContextShared"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
            ],
            resources: [
                .process("openapi.yaml"),
                .process("openapi-generator-config.yaml"),
            ],
            plugins: [
                .plugin(name: "DomainEventGeneratorPlugin", package: "swift-ddd-kit"),
                .plugin(name: "ModelGeneratorPlugin", package: "swift-ddd-kit"),
                .plugin(name: "OpenAPIGenerator", package: "swift-openapi-generator"),
            ]
        ),
        .executableTarget(
            name: "IAMContextServer",
            dependencies: [
                .target(name: "EmployeeAccessAggregate"),
                .target(name: "IAMContextShared"),
                .target(name: "Generated"),
                .product(name: "DDDKit", package: "swift-ddd-kit"),
                .product(name: "Hummingbird", package: "hummingbird"),
                .product(name: "OpenAPIHummingbird", package: "swift-openapi-hummingbird"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "Logging", package: "swift-log"),
                .product(name: "GRPCCore", package: "grpc-swift-2"),
                .product(name: "GRPCServiceLifecycle", package: "grpc-swift-extras"),
                .product(name: "GRPCNIOTransportHTTP2", package: "grpc-swift-nio-transport"),
                .product(name: "GRPCProtobuf", package: "grpc-swift-protobuf"),
            ]
        ),
        // protoc-generated gRPC contract for proto/PermissionsService.proto.
        // Regenerate (do NOT hand-edit) with protoc + protoc-gen-swift + protoc-gen-grpc-swift-2:
        //   protoc --swift_out=Sources/Generated --swift_opt=Visibility=Package \
        //          --grpc-swift-2_out=Sources/Generated --grpc-swift-2_opt=Visibility=Package \
        //          -I proto proto/PermissionsService.proto
        .target(
            name: "Generated",
            dependencies: [
                .product(name: "GRPCProtobuf", package: "grpc-swift-protobuf"),
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ]
        ),
        // One-shot data importer: reads a staff JSON file and enrolls each staff
        // via the CreateUserAccessProfile use-case. Lives inside this package so it
        // can reach the `package`-level application service / repository directly.
        .executableTarget(
            name: "EnrollStaffs",
            dependencies: [
                .target(name: "EmployeeAccessAggregate"),
                .target(name: "IAMContextShared"),
                .product(name: "DDDKit", package: "swift-ddd-kit"),
            ]
        ),
        // One-shot correction: revokes the placeholder permissions that
        // createUserAccessProfile granted, emitting a PrivilegeRevoked event per staff
        // (so each profile ends with an empty permission set). Same-package access to the
        // `package`-level RevokePrivilege application service.
        .executableTarget(
            name: "RevokeAllPrivileges",
            dependencies: [
                .target(name: "EmployeeAccessAggregate"),
                .target(name: "IAMContextShared"),
                .product(name: "DDDKit", package: "swift-ddd-kit"),
            ]
        ),
        .target(
            name: "IAMContextShared"
        ),
        .testTarget(
            name: "IAMContextTests",
            dependencies: ["EmployeeAccessAggregate", "IAMContextShared",
                .product(name: "TestUtility", package: "swift-ddd-kit")]
        ),
    ],
    swiftLanguageModes: [.v5]
)
