// swift-tools-version: 6.0
// Generated by Genesis v0.1.0-phase1k2.
import PackageDescription

let package = Package(
    name: "IAMContext",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        .library(name: "EmployeeAccessAggregate", targets: ["EmployeeAccessAggregate"]),
        .executable(name: "IAMContextServer", targets: ["IAMContextServer"]),
        .library(name: "IAMContextShared", targets: ["IAMContextShared"]),
        // permission codegen plugins（給各 context 消費；原 PermissionKit）：
        // PermissionGenPlugin：1 份 *permissions.yaml → Permission.swift + PermissionRules.swift（執法用，OC 採用中）
        // PermissionCatalogPlugin：多份 yaml → 一份 PermissionCatalog.swift（聚合，IAMPermissionCatalog target 用）
        .plugin(name: "PermissionGenPlugin", targets: ["PermissionGenPlugin"]),
        .plugin(name: "PermissionCatalogPlugin", targets: ["PermissionCatalogPlugin"]),
    ],
    dependencies: [
        // Range widened to admit DDDKit 1.x for DOWNSTREAM consumers only (e.g. EvidencePurchaseContext,
        // which is on 1.x). Each consumer's ROOT resolution picks its own line — OC stays 0.x, EPC gets 1.x.
        // Consumers of IAMContext only build the DDDKit-FREE codegen targets (PermissionGenPlugin →
        // permission-gen → PermissionGenerator, closure = Yams + ArgumentParser), so IAM's domain targets
        // are never compiled in their graph.
        // ⚠️ IAMContext's OWN domain code does NOT yet compile against DDDKit 1.x — this repo MUST stay
        // pinned on 0.x via the committed Package.resolved. Do NOT `swift package update` onto 1.x.
        .package(url: "https://github.com/gradyzhuo/swift-ddd-kit.git", "0.3.0" ..< "2.0.0"),
        .package(url: "https://github.com/apple/swift-openapi-generator", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-openapi-runtime", from: "1.0.0"),
        .package(url: "https://github.com/swift-server/swift-openapi-hummingbird", from: "2.0.0"),
        .package(url: "https://github.com/hummingbird-project/hummingbird", from: "2.0.0"),
        .package(url: "https://github.com/apple/swift-log", from: "1.0.0"),
        .package(url: "https://github.com/grpc/grpc-swift-2.git", from: "2.0.0"),
        .package(url: "https://github.com/grpc/grpc-swift-nio-transport.git", from: "2.0.0"),
        .package(url: "https://github.com/grpc/grpc-swift-protobuf.git", from: "2.0.0"),
        .package(url: "https://github.com/grpc/grpc-swift-extras.git", from: "2.1.0"),
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.33.3"),
        // HTTP 端管理員 token 守門（AdminTokenMiddleware）需讀 Authorization header；
        // swift-http-types 已在 Package.resolved（Hummingbird 傳遞依賴），此處僅顯式暴露 product。
        .package(url: "https://github.com/apple/swift-http-types", from: "1.0.0"),
        // permission codegen（原獨立 PermissionKit，2026-06-12 併入本 package——user 決策：
        // 現階段 codegen 是小功能、IAM 版本與其綁定，變大再考慮拆分）所需：
        .package(url: "https://github.com/jpsim/Yams.git", from: "5.1.3"),
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.3.0"),
    ],
    targets: [
        .target(
            name: "EmployeeAccessAggregate",
            dependencies: [
                .product(name: "DDDKit", package: "swift-ddd-kit"),
                .target(name: "IAMContextShared"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
            ],
            resources: [
                .process("openapi.yaml"),
                .process("openapi-generator-config.yaml"),
            ],
            plugins: [
                .plugin(name: "DomainEventGeneratorPlugin", package: "swift-ddd-kit"),
                .plugin(name: "ModelGeneratorPlugin", package: "swift-ddd-kit"),
                .plugin(name: "OpenAPIGenerator", package: "swift-openapi-generator"),
            ]
        ),
        .executableTarget(
            name: "IAMContextServer",
            dependencies: [
                .target(name: "EmployeeAccessAggregate"),
                .target(name: "IAMContextShared"),
                .target(name: "Generated"),
                .target(name: "IAMPermissionCatalog"),
                .product(name: "DDDKit", package: "swift-ddd-kit"),
                .product(name: "Hummingbird", package: "hummingbird"),
                .product(name: "OpenAPIHummingbird", package: "swift-openapi-hummingbird"),
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "Logging", package: "swift-log"),
                .product(name: "GRPCCore", package: "grpc-swift-2"),
                .product(name: "GRPCServiceLifecycle", package: "grpc-swift-extras"),
                .product(name: "GRPCNIOTransportHTTP2", package: "grpc-swift-nio-transport"),
                .product(name: "GRPCProtobuf", package: "grpc-swift-protobuf"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
            ]
        ),
        // protoc-generated gRPC contract for proto/PermissionsService.proto.
        // Regenerate (do NOT hand-edit) with protoc + protoc-gen-swift + protoc-gen-grpc-swift-2:
        //   protoc --swift_out=Sources/Generated --swift_opt=Visibility=Package \
        //          --grpc-swift-2_out=Sources/Generated --grpc-swift-2_opt=Visibility=Package \
        //          -I proto proto/PermissionsService.proto
        .target(
            name: "Generated",
            dependencies: [
                .product(name: "GRPCProtobuf", package: "grpc-swift-protobuf"),
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ]
        ),
        // NOTE: the one-shot staff backfill tools (EnrollStaffs / RevokeAllPrivileges) were moved out
        // to ContextPlayground as `IAMContextPart` (HTTP importer) on 2026-06-12 — they belong with the
        // rest of the all_staffs.json roster import tooling, and can't live in-process there (IAM's
        // gradyzhuo/swift-ddd-kit fork clashes with ContextPlayground's Mendesky/DDDKit). See
        // docs/grpc-auth-contract.md sibling note / ContextPlayground Sources/IAMContextPart.
        .target(
            name: "IAMContextShared"
        ),
        // 全 context 權限的聚合 catalog：PermissionCatalogPlugin 在 build 時讀本 target 內所有
        // *permissions.yaml（各 context SSOT 的手動複製快照，IAM 自身無 catalog）→ 產 PermissionCatalog.swift。
        // 供未來 role 設計 / 授權 UI 的權限選單（universe）；yaml 同步機制留待部署期定案。
        .target(
            name: "IAMPermissionCatalog",
            plugins: [
                .plugin(name: "PermissionCatalogPlugin"),
            ]
        ),
        // ── permission codegen（原獨立 PermissionKit，併入；詳見 docs/permission-codegen/）──
        .target(
            name: "PermissionGenerator",
            dependencies: [
                .product(name: "Yams", package: "Yams"),
            ]
        ),
        .executableTarget(
            name: "permission-gen",
            dependencies: [
                "PermissionGenerator",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ]
        ),
        .executableTarget(
            name: "permission-catalog-gen",
            dependencies: [
                "PermissionGenerator",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ]
        ),
        .plugin(
            name: "PermissionGenPlugin",
            capability: .buildTool(),
            dependencies: ["permission-gen"]
        ),
        .plugin(
            name: "PermissionCatalogPlugin",
            capability: .buildTool(),
            dependencies: ["permission-catalog-gen"]
        ),
        .testTarget(
            name: "PermissionGeneratorTests",
            dependencies: ["PermissionGenerator"],
            resources: [.copy("Fixtures")]
        ),
        .testTarget(
            name: "IAMContextTests",
            dependencies: ["EmployeeAccessAggregate", "IAMContextShared", "IAMContextServer", "Generated",
                "IAMPermissionCatalog",
                .product(name: "GRPCCore", package: "grpc-swift-2"),
                .product(name: "TestUtility", package: "swift-ddd-kit")]
        ),
        // 一次性遷移腳本（spec `docs/tasks/2026-09-03-firm-format-and-scope-check.md` Step 1-2）：
        // 把既有 EmployeeAccess 的 firm 從名稱轉統編。path 指到 scripts/migrations/ 而非 Sources/，
        // 讓腳本與其他一次性維運工具放在同一個慣例位置，同時仍受 SwiftPM 編譯與型別檢查。
        // ⚠️ 只提供程式碼，不在任何 CI/build 流程中自動執行；執行由人手動 `swift run MigrateFirmFormat` 決定時機。
        .executableTarget(
            name: "MigrateFirmFormat",
            dependencies: [
                .target(name: "EmployeeAccessAggregate"),
                .target(name: "IAMContextShared"),
                .product(name: "DDDKit", package: "swift-ddd-kit"),
            ],
            path: "scripts/migrations/MigrateFirmFormat"
        ),
    ],
    swiftLanguageModes: [.v5]
)
