//
//  PermissionCatalogEmitter.swift
//  PermissionKit
//
//  Aggregation emitter: many context permission documents -> ONE enumerable, structured catalog
//  (PermissionCatalog.swift). Reads only the `permissions:` (catalog) of each document — rules are
//  ignored. Pure data, no Middleware/runtime types, so the consuming target needs no extra deps.
//
//  Intended for an aggregator (e.g. IAM) that needs to know ALL contexts' permissions for role
//  design and a permission-granting UI — NOT for a context enforcing its own routes (use
//  PermissionEmitter / PermissionGenPlugin for that).
//

import Foundation

public struct PermissionCatalogEmitter {
    public let documents: [PermissionDocument]

    public init(documents: [PermissionDocument]) {
        self.documents = documents
    }

    private struct Record {
        let context: String
        let slot: String
        let operationId: String
        let rawValue: String
        let description: String?
    }

    private static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
    }

    public func render() -> String {
        var records: [Record] = []
        var seen = Set<String>()  // dedup by rawValue (context prefix keeps these globally unique)
        for doc in documents {
            for e in doc.permissions {
                let raw = "\(doc.context).\(e.slot).\(PermissionEmitter.pascal(e.operationId))"
                if seen.contains(raw) { continue }
                seen.insert(raw)
                records.append(Record(context: doc.context, slot: e.slot,
                                       operationId: e.operationId, rawValue: raw, description: e.description))
            }
        }
        records.sort { $0.rawValue < $1.rawValue }
        let contexts = Set(records.map(\.context)).sorted()

        var lines: [String] = []
        lines.append("// AUTO-GENERATED by PermissionKit (permission-catalog-gen). DO NOT EDIT.")
        lines.append("// Aggregated permission catalog across \(contexts.count) context(s); \(records.count) permission(s).")
        lines.append("// Source of truth: the per-context permission YAMLs. Regenerated by `swift build` via PermissionCatalogPlugin.")
        lines.append("")
        lines.append("/// One permission in the cross-context catalog (pure data: no routing/rules).")
        lines.append("public struct PermissionInfo: Sendable, Hashable, Codable {")
        lines.append("    public let context: String")
        lines.append("    public let slot: String")
        lines.append("    public let operationId: String")
        lines.append("    public let rawValue: String")
        lines.append("    public let description: String?")
        lines.append("    public init(context: String, slot: String, operationId: String, rawValue: String, description: String?) {")
        lines.append("        self.context = context")
        lines.append("        self.slot = slot")
        lines.append("        self.operationId = operationId")
        lines.append("        self.rawValue = rawValue")
        lines.append("        self.description = description")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        lines.append("/// The aggregated catalog of every context's permissions — for role design + a granting UI.")
        lines.append("public enum PermissionCatalog {")
        lines.append("    public static let all: [PermissionInfo] = [")
        for r in records {
            let desc = r.description.map { "\"\(Self.escape($0))\"" } ?? "nil"
            lines.append("        PermissionInfo(context: \"\(r.context)\", slot: \"\(r.slot)\", operationId: \"\(r.operationId)\", rawValue: \"\(r.rawValue)\", description: \(desc)),")
        }
        lines.append("    ]")
        lines.append("")
        lines.append("    /// All context names present in the catalog (sorted).")
        lines.append("    public static let contexts: [String] = [\(contexts.map { "\"\($0)\"" }.joined(separator: ", "))]")
        lines.append("")
        lines.append("    /// The universe of valid permission rawValues — e.g. to validate a grant.")
        lines.append("    public static let allRawValues: Set<String> = Set(all.map(\\.rawValue))")
        lines.append("")
        lines.append("    public static func permissions(inContext context: String) -> [PermissionInfo] {")
        lines.append("        all.filter { $0.context == context }")
        lines.append("    }")
        lines.append("")
        lines.append("    public static func permissions(inSlot slot: String) -> [PermissionInfo] {")
        lines.append("        all.filter { $0.slot == slot }")
        lines.append("    }")
        lines.append("}")

        return lines.joined(separator: "\n") + "\n"
    }
}
