# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: swift build testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["6.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
           swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true   
      - run: bash ./scripts/projection.sh
      - run: ulimit -n 10000
      - name: Build 
        run: swift build --build-tests --enable-code-coverage
      - name: Swift Testing
        run: swift test -v --skip-build --no-parallel --disable-xctest --enable-swift-testing
    services:
    # Label used to access the service container
      kurrentdb:
      # Docker Hub image
        image: docker.kurrent.io/kurrent-latest/kurrentdb:26.0
        ports:
          - "2113:2113"
        env:
          KURRENTDB_CLUSTER_SIZE: 1
          KURRENTDB_RUN_PROJECTIONS: All
          KURRENTDB_START_STANDARD_PROJECTIONS: true
          KURRENTDB_NODE_PORT: 2113
          KURRENTDB_INSECURE: true
          KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP: true
          KURRENTDB_ADVERTISE_HOST_TO_CLIENT_AS: 127.0.0.1 
